#pragma config(Sensor, dgtl1,  SkyClaw,            sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "DriveControler.c"
void AutoSky(){
	driveForward(2);
	SensorValue[SkyClaw] = 1;
	turnRight(4);
  SensorValue[SkyClaw] = 1;

}
void AutoCube(){
	driveForward(3);


}
